#!/bin/sh

if ! docker images 2> /dev/null | grep -q anysched-cli; then
    echo "Building docker image..."
    docker build -t anysched-cli .
fi

exec docker run \
    -v $(pwd)/anysched-cli.yaml:/workdir/anysched-cli.yaml \
    -v ~/.kube:/root/.kube \
    -it \
    --rm \
    anysched-cli \
    "$@"
